app/Http/routes.php
<?php
use Illuminate\Http\Request;
/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/
//chrome.exe --user-data-dir="C:/Chrome dev session" --disable-web-security



/* ------------------------------ Route User ------------------------------ */

Route::get('/', 'HomeController@index');

Route::get('/home', 'HomeController@index');

Route::get('/about', 'AboutusController@index');

Route::get('/services', 'ServicesController@index');

Route::get('/blog', 'BlogController@index');

Route::get('/contact', 'ContactController@index');

Route::get('/gallery', 'GalleryController@index');

Route::get('/gallery/image', 'GalleryController@image');

Route::get('/gallery/video', 'GalleryController@video');

Route::get('/login', 'LoginController@index');

Route::post('/login', 'LoginController@loginUser');

Route::get('/user', 'UserController@index');

Route::get('/register', 'RegisterController@index');

Route::post('/register', 'RegisterController@process');

Route::get('/userinfor', 'RegisterController@user');

Route::get('/logout', 'LoginController@logoutUser');

/* ------------------------------ End Route USer ------------------------------ */


/* ------------------------------ Route Admin ------------------------------ */


Route::get('/admin', 'LoginController@admin');

Route::post('/admin', 'LoginController@login');

Route::get('/admin/main', 'MainController@index');

/* ---------------------------------- Main Page -------------------------------------------*/

    Route::get('/admin/logout', 'LoginController@logout');
    
    Route::get('/admin/bill', 'MainBillController@bill');
    
    Route::get('/admin/customerinfo', 'MainCustomerController@customerinfo');
    
    Route::get('/admin/customerdate', 'MainCustomerController@customerdate');
    
    Route::get('/admin/customer', 'MainCustomerController@customer');
    
    Route::post('/admin/customer', 'MainCustomerController@customer');
    
    Route::get('/admin/newhome', 'MainNewController@newhome');
    
    Route::get('/admin/createnew', 'MainNewController@createnewhome');
    
    Route::get('/admin/edithome', 'MainNewController@edithome');
    
    Route::post('/admin/posts', 'MainNewController@post');
    
    Route::get('/admin/newblog', 'MainNewController@newblog');
    
    Route::get('/admin/newservice', 'MainNewController@newservice');
    
    Route::get('/admin/employeetour', 'MainEmployeeController@employeetour');
    
    Route::get('/admin/employee', 'MainEmployeeController@employee');
    
    Route::get('/admin/servicecategory', 'MainServicesController@servicecategory');
    
    Route::get('/admin/servicesub', 'MainServicesController@servicesub');
    
    Route::get('/admin/image', 'MainImageController@image');
    
    Route::get('/admin/video', 'MainVideoController@video');
    
    Route::get('/admin/point', 'MainCareController@point');
    
    Route::get('/admin/contact', 'MainCareController@contact');
    
    Route::get('/admin/revenue', 'MainExportController@revenue');
    
    Route::get('/admin/salaries', 'MainExportController@salaries');
    
    Route::get('/admin/revenexpen', 'MainExportController@revenexpen');
    
    Route::get('/admin/customersta', 'MainExportController@customersta');
    
    Route::get('/admin/servicessta', 'MainExportController@servicessta');

/* ---------------------------------- End Main Page -------------------------------------------*/


/* ------------------------------ End Route Admin ------------------------------ */

    Route::get('/admin/homeBlog/{keyword?}/{status?}','BlogController@blogHome');
    
    Route::get('/admin/createblog/{bien?}','BlogController@createBlog');
    
     Route::get('/admin/deleteblog/{bien?}','BlogController@deleteblog');
    
    Route::post('image-upload','BlogController@imageUploadPost');
    
    Route::get('getImages','BlogController@getImages');
    
    Route::post('createBlogPost','BlogController@createBlogPost');
    
    Route::post('searchBlogPost','BlogController@searchBlogPost');
    
/* ------------------------------------- Api ----------------------------------------- */
/* ----- Category -------- */
/* ------------ Load --------- */
Route::get('api/getCategory','ApiController@getCategory');

/* ------------End Load --------- */

/* ------------ Create --------- */
Route::post('api/createCategory','ApiController@createCategory');

/* ------------End Create --------- */

/* ------------ Edit --------- */
Route::post('api/editCategory','ApiController@editCategory');

/* ------------End Edit --------- */

/* ------------ Del --------- */
Route::post('api/delCategory','ApiController@delCategory');

/* ------------End Del --------- */



/* ----- Sub -------- */
/* ------------ Load --------- */
Route::get('api/getSub','ApiController@getSub');
/* ------------End Load --------- */

/* ------------ Create --------- */
Route::post('api/createSub','ApiController@createSub');
/* ------------End Create --------- */

/* ------------ Edit --------- */
Route::post('api/editSub','ApiController@editSub');
/* ------------End Edit --------- */

/* ------------ Del --------- */
Route::post('api/delSub','ApiController@delSub');
/* ------------End Del --------- */

/* ------------------------------------- End Api ----------------------------------------- */

app/Models/ProductShip.php
<?php 
namespace App\Models;
  
use Illuminate\Database\Eloquent\Model;
  
class ProductShip extends Model{
    
    const TABLE_PRODUCTSHIP = 'detailrelationship';
    
    const PRODUCTSHIP_ID = 'Idproduct';
    
    const PRODUCTSHIP_RLS = 'Idproduct_rls';
    
    const PRODUCTSHIPID = 'id';
    
    private $id = 'id';
    
    private $idproduct = 'Idproduct';
    
    private $idproduct_rls = 'Idproduct_rls';
    
    public function __construct(){
        
    }
    
    public function setId($id){
        $this->id = $id;
    }
    
    public function getId(){
        return $this->id;
    }
    
    public function setName($idproduct){
        $this->idproduct = $idproduct;
    }
    
    public function getName(){
        return $this->idproduct;
    }
    
}
?>

app/Http/Controllers/ServicesController.php
<?php
namespace App\Http\Controllers;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\DB;
use Illuminate\Http\Request;
use Session;
use App\Http\Database\themes;

class ServicesController extends Controller {
    
    /**
	 * Create a new controller instance.
	 *
	 * @return void
	 */
	public function __construct()
	{
		$this->middleware('guest');
	}

	/**
	 * Show the application welcome screen to the user.
	 *
	 * @return Response
	 */
	public function index()
	{
        $nameThemes = themes::getThemesPresent();
        
        $array = array('themes'=> $nameThemes,'url' =>'services');

        return view('themes/'.$nameThemes.'/user/services')->with('arrayBase',$array);
	}
}

resources/views/admin/pages/services/index.blade.php
@extends('admin.main')

@section('css')
@endsection

@section('content')
	<section id="service" class="content">
		<div class="row">
			<div class="col-md-5">
				<div class="box">
					<div class="box-header with-border">
						<div class="col-xs-5">
							<h2>Danh mục</h2>
						</div>
						<div class="col-xs-7">
							<button type="button" 
								class="btn bg-maroon btn-flat margin pull-right" 
								data-toggle="modal" 
								data-target="#add-category"
							>
								Thêm danh mục
							</button>
						</div>
					</div>
					<div class="box-body">
						<table class="table table-striped">
							<thead>
								<tr>
									<th>STT</th>
									<th>Tên </th>
									<th>Chức năng</th>
								</tr>
							</thead>
							<tbody>
								<tr v-for="category in categories">
									<td>@{{ $index + 1 }}</td>
									<td>@{{ category.name }}</td>
									<td>
										<div class="btn-group">
											<button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
												<i class="fa fa-cogs"></i>
											</button>
											<ul class="dropdown-menu pull-right" role="menu">
												<li><a data-toggle="modal" data-target="#info-category">Xem chi tiết</a></li>
												<li><a data-toggle="modal" data-target="#add-category">Chỉnh sửa</a></li>
												<li><a href="#">Xóa</a></li>
											</ul>
										</div>
									</td>
								</tr>
							</tbody>
						</table>
					</div>
				</div>
			</div>

			<div class="col-md-7">
				<div class="box">
					<div class="box-header with-border">
						<div class="col-xs-4">
							<div class="form-group">
								<h2>Dịch vụ</h2>
								<label>Danh mục:</label>
								<select class="form-control">
									<option value="">Tất cả</option>
									<option>option 1</option>
									<option>option 2</option>
									<option>option 3</option>
									<option>option 4</option>
									<option>option 5</option>
								</select>
							</div>
						</div>
						<div class="col-xs-8">
							<button type="button" class="btn bg-maroon btn-flat margin pull-right">Thêm dịch vụ</button>
						</div>
					</div>
					<div class="box-body">
						<table class="table table-striped">
						<thead>
							<tr>
								<th>STT</th>
								<th>Tên </th>
								<th>Hoa hồng</th>
								<th>Gía</th>
								<th>Chức năng</th>
							</tr>
						</thead>
						<tbody>
							<tr v-for="sub in sub_categories">
								<td>@{{ $index + 1 }}</td>
								<td>@{{ sub.name }}</td>
								<td>@{{ sub.income }}</td>
								<td>@{{ sub.price | number }}</td>
								<td>
									<div class="btn-group">
										<button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
											<i class="fa fa-cogs"></i>
										</button>
										<ul class="dropdown-menu pull-right" role="menu">
											<li><a data-toggle="modal" data-target="#info-category">Xem chi tiết</a></li>
											<li><a data-toggle="modal" data-target="#add-category">Chỉnh sửa</a></li>
											<li><a href="#">Xóa</a></li>
										</ul>
									</div>
								</td>
							</tr>
						</tbody>
						</table>
					</div>
				</div>
			</div>
		</div>
	</section>

	<div class="modal modal-info fade" id="info-category" tabindex="-1" role="dialog" >
		<div class="modal-dialog">
			<div class="modal-content">
				<div class="modal-header">
					<button type="button" class="close" data-dismiss="modal" aria-label="Close">
					<span aria-hidden="true">&times;</span></button>
					<h4 class="modal-title">Info Modal</h4>
				</div>
				<div class="modal-body">
					<p>One fine body&hellip;</p>
				</div>
				<div class="modal-footer">
					<button type="button" class="btn btn-outline pull-left" data-dismiss="modal">Close</button>
					<button type="button" class="btn btn-outline">Save changes</button>
				</div>
			</div>
		</div>
	</div>

	<div class="modal fade" id="add-category" tabindex="-1" role="dialog" >
		<div class="modal-dialog">
			<div class="modal-content">
				<div class="modal-header">
					<button type="button" class="close" data-dismiss="modal" aria-label="Close">
						<span aria-hidden="true">×</span>
					</button>
					<h4 class="modal-title">Thêm</h4>
				</div>

				<div class="modal-body">
					<div class="row">
						<div class="col-sm-12">
							<div class="form-horizontal">
								<div class="form-group">
									<label for="name-category" class="col-sm-4 control-label">Tên</label>
									<div class="col-sm-8">
										<input type="text" class="form-control" id="name-category" placeholder="Email">
									</div>
				                </div>
				                <div class="form-group">
									<label for="pice" class="col-sm-4 control-label">Gía</label>
									<div class="col-sm-8">
										<input type="number" class="form-control" id="pice" placeholder="">
									</div>
				                </div>
				                <div class="form-group">
									<label for="discount" class="col-sm-4 control-label">Hoa hồng</label>
									<div class="col-sm-8">
										<input type="number" class="form-control" id="discount" placeholder="">
									</div>
				                </div>
				                <div class="form-group">
									<label for="discount" class="col-sm-4 control-label">Thông tin dịch vụ</label>
									<div class="col-sm-8">
										<textarea class="form-control" rows="3" placeholder="Nhập ..."></textarea>
									</div>
				                </div>
				           	</div>
						</div>
					</div>
				</div>

				<div class="modal-footer">
					<button type="button" class="btn btn-default pull-left" data-dismiss="modal">Thoát</button>
					<button type="button" class="btn btn-primary">Thêm</button>
				</div>
			</div>
		</div>
	</div>
@endsection

@section('js')
	<script src="{{asset('/public/dist/js/service.js')}}"></script>
@endsection